### ISSUE TITLE
Google Safe Browsing/VirusTotal false positive

### ISSUE THREAD

**Issue by GreyHak** [programmer2514/DPEdit-GUI#1]
Firefox reports that v1.0.2's executable contains a virus.

**Comment by programmer2514** [comment]
This is a false positive (heuristic analysis often detects downloaders as trojans).

I have released a hotfix that should mitigate the issue, but I can't guarantee that it will be a permanent fix. I *can* guarantee that neither this application nor its command line counterpart contain viruses, as you can simply read/compile the source code yourself.

**Comment by luxalpa** [comment]
This issue still persists. My issue with this is that it could mark an actual infection of the executable (for example if your account was compromised or there was a man-in-the-middle). I could trust this on my home PC, but I can't use this on my work PC which has sensititve company info. Would be awesome if there could be a fix for this. :)

But no pressure, I'll try using the CLI, which does not appear to have this problem for some reason.

**Comment by programmer2514** [comment]
@luxalpa The CLI tool will not encounter this issue as it does not contain an auto-updater. Unfortunately, this is not an issue I am capable of resolving. If you would like to help out, feel free to report the false positive to the appropriate source(s):

- Microsoft: https://www.microsoft.com/en-us/wdsi
- Google: https://safebrowsing.google.com/safebrowsing/report_error/

It does appear that [VirusTotal's number of false positives has drastically improved](https://www.virustotal.com/gui/url/962c2fd87fa4fb0b04be3c28987191fcc4b8b61e48c56df8f86c2c300550804d/detection) so it really just seems to be a waiting game.
